services:
  tower-db:
    image: postgres:alpine
    container_name: tower-db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 1s
      timeout: 1s
      retries: 15
    volumes:
      - tower-db-data:/var/lib/postgresql/data

  tower:
    container_name: tower
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: always
    depends_on:
      - tower-db
    links:
      - tower-db
    ports:
      - '3100:3100'
    env_file:
      - .env.docker
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma

volumes:
  tower-db-data: